In [1]:
import pandas as pd

data = {"Id_producto": [1001, 1002, 1003, 1003],
        "Cantidad_vendida": [30, None, 25, 25],
        "Precio": [20.5, 15.0, None, 22.5]}

df = pd.DataFrame(data)
df

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5

In [2]:
df.head()

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id_producto       4 non-null      int64
 1   Cantidad_vendida  3 non-null      float64
 2   Precio            3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes

In [4]:
df.isnull()
# Devuelve True cuando encuentra un dato vacio

   Id_producto  Cantidad_vendida  Precio
0        False             False   False
1        False              True   False
2        False             False    True
3        False             False   False

In [5]:
df.isnull().sum()
# devuelve cuantos nulos tiene cada serie del dataframe

Id_producto         0
Cantidad_vendida    1
Precio              1
dtype: int64